{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "sympauthy.fullnames.auth" . }}
  labels:
    {{- include "sympauthy.labels.auth" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sympauthy.fullnames.auth" . }}
  minReplicas: {{ .Values.autoscaling.auth.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.auth.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.auth.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.auth.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.auth.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.auth.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
