{{- if .Values.secrets.auth }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sympauthy.secrets.auth" . }}
  labels:
    {{- include "sympauthy.labels.auth" . | nindent 4 }}
stringData:
  application.yml: |
    {{ toYaml .Values.secrets.auth | b64enc }}
{{- end }}
