apiVersion: v1
kind: Service
metadata:
  name: {{ include "sympauthy.fullnames.auth" . }}
  labels:
    {{- include "sympauthy.labels.auth" . | nindent 4 }}
spec:
  type: {{ .Values.services.auth.type }}
  ports:
    - port: {{ .Values.services.auth.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sympauthy.selectorLabels.auth" . | nindent 4 }}
